version: '3.8'

services:

  db:
    image: postgres:latest
    container_name: cont-postgres
    restart: always
    ports:
      - "5433:5432" # Host-Port : Container-Port
    environment:
      POSTGRES_PASSWORD: FinalProject123
      POSTGRES_DB: final_project

# NOTE:
# - The `CONTROLLER` Listener CANNOT be "Advertised", however it must be a Listener
# - Listeners define where the Kafka broker listens for connections
# - Advertised Listeners define how clients (e.g., other docker containers, Spring/Java
# ... components, etc.) connect to the Kafka broker
  kafka:
    image: apache/kafka:3.7.0
    container_name: cont-kafka-broker
    restart: always
    ports:
      - "9092:9092" # Host-Port : Container-Port
      - "9093:9093" # Host-Port : Container-Port
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS:
        LISTENER_INTERNAL://kafka:29092,LISTENER_EXTERNAL://kafka:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS:
        LISTENER_INTERNAL://kafka:29092,LISTENER_EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP:
        LISTENER_INTERNAL:PLAINTEXT,LISTENER_EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_INTERNAL
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3


  schema-registry:
    image: confluentinc/cp-schema-registry:7.4.0
    container_name: cont-schema-registry
    depends_on:
      - kafka
    ports:
      - "8081:8081" # Host-Port : Container-Port
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:29092
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: cont-kafka-ui
    depends_on:
      - kafka
      - schema-registry
    ports:
      - "8090:8080" # Host-Port : Container-Port
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: not-used
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema-registry:8081